server:
  port: 8080
spring:
  application:
#    应用名称、可选
    name: reggie_take_out
#    数据源信息（数据库连接）
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
#      (mac环境)
      password: yehanyu123

#      本机linux虚拟机redis
  redis:
    host: 192.168.142.100
    password: 123456
    port: 6379
    database: 0
#    使用redis，配合springcache；设置缓存过期时间5分钟
  cache:
    redis:
      time-to-live: 300000

mybatis-plus:
  configuration:
    #在映射 实体 or 属性时，将数据库中 表名 or 字段名 中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#    mybatis-plus 自动分配实体类id，分配策略：除了 ASSIGN_ID 策略外，Mybatis-Plus 还支持 AUTO（自增）、ID_WORKER（雪花算法）、UUID 和 NONE 四种主键生成策略。
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  file:
# basepath 需要用\隔开目录，该字符串后面要继续拼接字符串
    basePath: f:\testDir\